#!/bin/bash
#
# Fonts-Installer
##########################################################################
#                        Nautilus Fonts Installer                        #
##########################################################################
#                                                                        #
# Created by Federico Vecchio (Vecna)                                    #
#                                                                        #
##########################################################################
# This program is free software; you can redistribute it and/or modify   #
# it under the terms of the GNU General Public License as published by   #
# the Free Software Foundation; version 2 of the License.
#                                                                        #
# This program is distributed in the hope that it will be useful,        #
# but WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the           #
# GNU General Public License for more details.                           #
#                                                                        #
# You should have received a copy of the GNU General Public License      #
# along with this program; if not, write to the Free Software            #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,		     #
# MA 02110-1301 USA							                             #
##########################################################################

# https://www.pling.com/p/1007676


# ---------------------
# Linguagem automática
# ---------------------

# Function to set language strings based on the system's language

set_language_strings() {

    case "$LANG" in

        it_IT* ) # Italian
            ok='Installazione font(s) completata'
            title_ok='Font Installer'
            title_wait='Aggiornamento'
            wait='Aggiornamento lista font in corso...'
            errors='Si sono verificati degli errori'
            title_errors='Errore'
            copying_fonts='Copia dei font in corso...'
            ;;

        fr_FR* ) # French
            ok='Installation des polices terminée'
            title_ok='Installateur de polices'
            title_wait='Mise à jour'
            wait='Mise à jour de la liste des polices...'
            errors='Des erreurs se sont produites'
            title_errors='Erreur'
            copying_fonts='Copie des polices en cours...'
            ;;

        es_ES* ) # Spanish
            ok='Instalación de fuentes completada'
            title_ok='Instalador de Fuentes'
            title_wait='Actualización'
            wait='Actualizando lista de fuentes...'
            errors='Se produjeron errores'
            title_errors='Error'
            copying_fonts='Copiando fuentes en progreso...'
            ;;

        de_DE* ) # German
            ok='Schriftarten-Installation abgeschlossen'
            title_ok='Schriftarten-Installer'
            title_wait='Aktualisierung'
            wait='Aktualisierung der Schriftartenliste...'
            errors='Es traten Fehler auf'
            title_errors='Fehler'
            copying_fonts='Kopiere Schriftarten...'
            ;;

        pt_PT* ) # Portuguese
            ok='Instalação de fontes concluída'
            title_ok='Instalador de Fontes'
            title_wait='Atualização'
            wait='Atualizando lista de fontes...'
            errors='Ocorreram erros'
            title_errors='Erro'
            copying_fonts='Copiando fontes em andamento...'
            ;;

        * ) # Default to English if system language not matched
            ok='Font(s) installation completed'
            title_ok='Font Installer'
            title_wait='Updating'
            wait='Updating font list...'
            errors='Errors occurred'
            title_errors='Error'
            copying_fonts='Copying fonts in progress...'
            ;;
    esac
}


# ---------------------
# Criar diretório
# ---------------------

create_dir() {
    [ -d "$HOME/.fonts" ] || mkdir -p "$HOME/.fonts"
}

# ---------------------
# Copiar fontes com progresso
# ---------------------

install_fonts() {
    total=$#
    count=0

    (
    for file in "$@"; do
        cp "$file" "$HOME/.fonts"
        count=$((count+1))
        echo $((count * 100 / total))
        sleep 0.1
    done
    ) | yad --center --progress --title="$title" --text="$copying" --percentage=0 --auto-close
}

# ---------------------
# Atualizar cache
# ---------------------

update_cache() {
    (
      fc-cache -fv
      echo "100"
    ) | yad --center --progress --title="$title" --text="$updating" --percentage=0 --auto-close
}

# ---------------------
# MAIN
# ---------------------

set_language_strings
create_dir
install_fonts "$@"
update_cache

yad --center --info --title="$title" --text="$ok"

exit 0
